"""Frozen previous Pi extension source body."""

from __future__ import annotations

from .pi_extension_approval_source import APPROVAL_RESUME_HELPERS_SOURCE


def build_previous_source_body(*, harness: str, display_name: str) -> str:
    return (
        "type GuardDaemonConnection = { port: number; authToken: string };\n" + "type GuardDaemonAttempt = {\n"  # pyright: ignore[reportImplicitStringConcatenation]
        "  response: GuardResponse | null;\n"
        "  recoveryKind: GuardDaemonRecoveryKind | null;\n"
        "};\n"
        "\n"
        "function normalizeGuardResponse(value: unknown): GuardResponse | null {\n"
        '  if (!value || typeof value !== "object" || Array.isArray(value)) return null;\n'
        "  const parsed = value as Record<string, unknown>;\n"
        "  if (parsed.reason !== undefined && parsed.reason !== null && "
        'typeof parsed.reason !== "string") return null;\n'
        '  if (parsed.decision === "allow" || parsed.decision === "deny") {\n'
        "    return parsed as GuardResponse;\n"
        "  }\n"
        '  if (parsed.decision === "block") {\n'
        '    return { ...parsed, decision: "deny" } as GuardResponse;\n'
        "  }\n"
        "  return null;\n"
        "}\n"
        "\n"
        "function fallbackGuardResponse(\n"
        "  reasonCode: string,\n"
        "  reason: string,\n"
        "): GuardResponse {\n"
        '  return { decision: "deny", reason, reason_code: reasonCode };\n'
        "}\n"
        "\n"
        "function daemonResponseCanReturn(\n"
        "  payload: Record<string, unknown>,\n"
        "  response: GuardResponse,\n"
        "): boolean {\n"
        '  if (payload.hook_event_name !== "PostToolUse") return true;\n'
        "  if (response.observe_mode === true) return true;\n"
        '  if (response.model_output_action === "replace_with_reviewed_excerpt") return true;\n'
        '  if (response.model_output_action === "allow_original") {\n'
        '    return typeof response.reviewed_output_sha256 === "string" &&\n'
        "      response.reviewed_output_sha256.length > 0;\n"
        "  }\n"
        '  if (response.decision === "allow" || response.decision === "deny") return true;\n'
        "  return false;\n"
        "}\n"
        "\n"
        "function loadGuardDaemonConnection(): GuardDaemonConnection | null {\n"
        "  let port = 0;\n"
        "  let authToken = '';\n"
        "  try {\n"
        "    const daemonState = JSON.parse(\n"
        "      readFileSync(join(GUARD_HOME, 'daemon-state.json'), 'utf8'),\n"
        "    ) as { compatibility_version?: unknown; package_version?: unknown; port?: unknown };\n"
        "    // Prefer protocol compatibility over exact package version. Exact package pins\n"
        "    // go stale after hol-guard update and force a cold CLI fallback that times out.\n"
        "    if (daemonState.compatibility_version !== GUARD_COMPATIBILITY_VERSION) return null;\n"
        "    port = typeof daemonState.port === 'number' ? daemonState.port : 0;\n"
        "    authToken = readFileSync(join(GUARD_HOME, 'daemon-auth-token'), 'utf8').trim();\n"
        "  } catch {\n"
        "    return null;\n"
        "  }\n"
        "  if (!(port > 0) || authToken.length === 0) return null;\n"
        "  return { port, authToken };\n"
        "}\n"
        "\n"
        "async function daemonGuardResponse(\n"
        "  serializedPayload: string,\n"
        "  cwd?: string,\n"
        "  timeoutMs: number = GUARD_DAEMON_TIMEOUT_MS,\n"
        "  deadlineAt?: number,\n"
        "): Promise<GuardDaemonAttempt> {\n"
        '  if (typeof fetch !== "function") {\n'
        '    return { response: null, recoveryKind: "transport-failure" };\n'
        "  }\n"
        "  const connection = loadGuardDaemonConnection();\n"
        '  if (!connection) return { response: null, recoveryKind: "transport-failure" };\n'
        '  const workspace = typeof cwd === "string" && cwd ? cwd : process.cwd();\n'
        "  const params = new URLSearchParams({ 'guard-home': GUARD_HOME });\n"
        "  if (workspace) params.set('workspace', workspace);\n"
        "  if (!GUARD_HOME_DIR_IS_DEFAULT && GUARD_HOME_DIR) params.set('home', GUARD_HOME_DIR);\n"
        "  const controller = typeof AbortController === 'function' ? new AbortController() : undefined;\n"
        "  const timeoutHandle = setTimeout(() => controller?.abort(), timeoutMs);\n"
        "  try {\n"
        "    let daemonPayload = serializedPayload;\n"
        "    try {\n"
        "      const parsedPayload = JSON.parse(serializedPayload) as Record<string, unknown>;\n"
        "      const remainingMs = deadlineAt === undefined ? timeoutMs : deadlineAt - Date.now();\n"
        "      parsedPayload.guard_remaining_ms = Math.min(60_000, Math.max(1, Math.min(timeoutMs, remainingMs)));\n"
        "      daemonPayload = JSON.stringify(parsedPayload);\n"
        "    } catch {}\n"
        f"    const response = await fetch(`http://127.0.0.1:${{connection.port}}"
        f"/v1/hooks/{harness}?${{params.toString()}}`, {{\n"
        "      method: 'POST',\n"
        "      headers: {\n"
        "        'Content-Type': 'application/json',\n"
        "        'X-Guard-Token': connection.authToken,\n"
        "      },\n"
        "      body: daemonPayload,\n"
        "      signal: controller?.signal,\n"
        "    });\n"
        "    if (!response.ok) {\n"
        "      let reasonCode = `daemon_http_${response.status}`;\n"
        "      try {\n"
        "        const errorPayload = JSON.parse((await response.text()).slice(0, GUARD_TEXT_LIMIT_CHARS)) as {\n"
        "          error?: unknown;\n"
        "        };\n"
        "        if (typeof errorPayload.error === 'string' && errorPayload.error) {\n"
        "          reasonCode = errorPayload.error;\n"
        "        }\n"
        "      } catch {}\n"
        "      if (response.status === 401 || response.status === 403) {\n"
        "        return {\n"
        "          response: null,\n"
        '          recoveryKind: "authenticated-control-plane-failure",\n'
        "        };\n"
        "      }\n"
        "      return {\n"
        "        response: {\n"
        '          decision: "deny",\n'
        "          reason: `HOL Guard could not safely review this action (${reasonCode}).`,\n"
        "          reason_code: reasonCode,\n"
        "        },\n"
        "        recoveryKind: null,\n"
        "      };\n"
        "    }\n"
        "    const raw = (await response.text()).trim();\n"
        '    if (!raw) return { response: null, recoveryKind: "transport-failure" };\n'
        "    try {\n"
        "      const parsed = JSON.parse(raw) as unknown;\n"
        "      const normalized = normalizeGuardResponse(parsed);\n"
        "      if (normalized !== null) {\n"
        "        return { response: normalized, recoveryKind: null };\n"
        "      }\n"
        '      return { response: null, recoveryKind: "transport-failure" };\n'
        "    } catch {}\n"
        "    return {\n"
        "      response: {\n"
        '        decision: "deny",\n'
        '        reason: "HOL Guard received an invalid response from the authenticated local daemon.",\n'
        '        reason_code: "daemon_invalid_response",\n'
        "      },\n"
        "      recoveryKind: null,\n"
        "    };\n"
        "  } catch (error) {\n"
        "    if (error instanceof Error && error.name === 'AbortError') {\n"
        "      // Classified transport recovery preserves a live overloaded daemon.\n"
        '      return { response: null, recoveryKind: "transport-failure" };\n'
        "    }\n"
        '    return { response: null, recoveryKind: "transport-failure" };\n'
        "  } finally {\n"
        "    clearTimeout(timeoutHandle);\n"
        "  }\n"
        "}\n"
        "\n"
        "async function runGuard(\n"
        "  payload: Record<string, unknown>,\n"
        "  cwd?: string,\n"
        "  options?: { enforceSizeCap?: boolean },\n"
        "): Promise<GuardResponse> {\n"
        "  const deadlineAt = Date.now() + GUARD_TIMEOUT_MS - GUARD_DEADLINE_RESERVE_MS;\n"
        "  const args = [...GUARD_ARGS];\n"
        '  const workspace = typeof cwd === "string" && cwd ? cwd : process.cwd();\n'
        '  if (workspace) args.push("--workspace", workspace);\n'
        "  let payloadToSend = payload;\n"
        "  let serializedPayload = '';\n"
        "  let cleanupPayloadReference = () => {};\n"
        "  try {\n"
        "    serializedPayload = JSON.stringify(payloadToSend);\n"
        "  } catch (error) {\n"
        "    return {\n"
        '      decision: "deny",\n'
        f"      reason: `HOL Guard could not serialize {display_name} hook payload: ${{\n"
        "        error instanceof Error ? error.message : String(error)\n"
        "      }`,\n"
        "    };\n"
        "  }\n"
        "  if (\n"
        "    options?.enforceSizeCap === true &&\n"
        "    serializedPayload.length > GUARD_MAX_SERIALIZED_PAYLOAD_CHARS\n"
        "  ) {\n"
        "    const referenced = referencedPayload(payloadToSend, serializedPayload);\n"
        "    payloadToSend = referenced.payload;\n"
        "    cleanupPayloadReference = referenced.cleanup;\n"
        "    try {\n"
        "      serializedPayload = JSON.stringify(payloadToSend);\n"
        "    } catch (error) {\n"
        "      cleanupPayloadReference();\n"
        "      return {\n"
        '        decision: "deny",\n'
        f"        reason: `HOL Guard could not serialize {display_name} hook payload reference: ${{\n"
        "          error instanceof Error ? error.message : String(error)\n"
        "        }`,\n"
        "      };\n"
        "    }\n"
        "  }\n"
        "  if (\n"
        "    options?.enforceSizeCap === true &&\n"
        "    serializedPayload.length > GUARD_MAX_SERIALIZED_PAYLOAD_CHARS\n"
        "  ) {\n"
        "    cleanupPayloadReference();\n"
        "    return {\n"
        '      decision: "deny",\n'
        f'      reason: "HOL Guard blocked this {display_name} hook payload before review because it exceeded '
        '"\n'
        '        + "the safe size limit.",\n'
        "    };\n"
        "  }\n"
        "  let daemonAttempt = await daemonGuardResponse(\n"
        "    serializedPayload, cwd, GUARD_DAEMON_TIMEOUT_MS, deadlineAt,\n"
        "  );\n"
        "  if (\n"
        "    daemonAttempt.response &&\n"
        "    daemonResponseCanReturn(payload, daemonAttempt.response)\n"
        "  ) {\n"
        "    cleanupPayloadReference();\n"
        "    return daemonAttempt.response;\n"
        "  }\n"
        "  if (daemonAttempt.response) {\n"
        '    daemonAttempt = { response: null, recoveryKind: "transport-failure" };\n'
        "  }\n"
        "  if (daemonAttempt.recoveryKind !== null) {\n"
        "    const recoveryTimeoutMs = Math.min(\n"
        "      GUARD_DAEMON_RECOVERY_TIMEOUT_MS,\n"
        "      Math.max(deadlineAt - Date.now(), 1),\n"
        "    );\n"
        "    if (await recoverGuardDaemon(recoveryTimeoutMs, daemonAttempt.recoveryKind)) {\n"
        "      daemonAttempt = await daemonGuardResponse(\n"
        "        serializedPayload,\n"
        "        cwd,\n"
        "        Math.min(GUARD_DAEMON_RETRY_TIMEOUT_MS, Math.max(deadlineAt - Date.now(), 1)),\n"
        "        deadlineAt,\n"
        "      );\n"
        "      if (\n"
        "        daemonAttempt.response &&\n"
        "        daemonResponseCanReturn(payload, daemonAttempt.response)\n"
        "      ) {\n"
        "        cleanupPayloadReference();\n"
        "        return daemonAttempt.response;\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "  if (guardCliContainmentFailed) {\n"
        "    cleanupPayloadReference();\n"
        "    return {\n"
        '      decision: "deny",\n'
        '      reason: "HOL Guard cannot safely start another fallback because prior child cleanup "\n'
        '        + "was not confirmed.",\n'
        '      reason_code: "guard_cli_containment_failed",\n'
        "    };\n"
        "  }\n"
        "  if (guardCliEvaluationInFlight) {\n"
        "    cleanupPayloadReference();\n"
        "    return {\n"
        '      decision: "deny",\n'
        '      reason: "HOL Guard recovery is already reviewing another action. Retry after it completes.",\n'
        '      reason_code: "guard_cli_recovery_busy",\n'
        "    };\n"
        "  }\n"
        "  guardCliEvaluationInFlight = true;\n"
        "  let result: GuardCliResult | null = null;\n"
        "  const cliTimeoutMs = Math.min(GUARD_CLI_TIMEOUT_MS, Math.max(deadlineAt - Date.now(), 1));\n"
        "  try {\n"
        "    result = await runGuardCliCommand(\n"
        "      GUARD_CLI_WRAPPER_COMMAND,\n"
        "      GUARD_CLI_WRAPPER_ACCEPTS_JSON_ARGS\n"
        "        ? [...GUARD_CLI_WRAPPER_ARGS, JSON.stringify(args)]\n"
        "        : args,\n"
        "      serializedPayload,\n"
        "      cliTimeoutMs,\n"
        "    );\n"
        "  } finally {\n"
        "    guardCliEvaluationInFlight = false;\n"
        "  }\n"
        "  cleanupPayloadReference();\n"
        "  if (result === null) {\n"
        "    return {\n"
        '      decision: "deny",\n'
        f'      reason: "HOL Guard {display_name} hook failed before completing review: '
        'Guard CLI was not found.",\n'
        "    };\n"
        "  }\n"
        "  if (result.error) {\n"
        "    const errorMessage = result.error.message;\n"
        "    const errorCode = typeof result.error.code === 'string' ? result.error.code : '';\n"
        "    if (errorCode === 'ETIMEDOUT') {\n"
        "      return {\n"
        '        decision: "deny",\n'
        f'        reason: "HOL Guard could not complete fallback review before the {display_name} '
        'deadline. Retry the action.",\n'
        '        reason_code: "guard_cli_recovery_timeout",\n'
        "      };\n"
        "    }\n"
        "    return {\n"
        '      decision: "deny",\n'
        f"      reason: `HOL Guard {display_name} hook failed before completing review: "
        "${errorMessage}`,\n"
        "    };\n"
        "  }\n"
        '  const lines = (result.stdout ?? "").split(/\\r?\\n/).map((line) => line.trim()).filter(Boolean);\n'
        "  const lastLine = lines.length > 0 ? lines[lines.length - 1] : null;\n"
        "  if (lastLine) {\n"
        "    try {\n"
        "      const parsed = JSON.parse(lastLine) as unknown;\n"
        "      const normalized = normalizeGuardResponse(parsed);\n"
        '      if (normalized !== null && (result.status === 0 || normalized.decision === "deny")) {\n'
        "        return normalized;\n"
        "      }\n"
        "    } catch {}\n"
        "  }\n"
        "  if (result.status !== 0) {\n"
        "    return {\n"
        '      decision: "deny",\n'
        '      reason: (result.stderr ?? "").trim() || "Blocked by HOL Guard.",\n'
        "    };\n"
        "  }\n"
        "  return fallbackGuardResponse(\n"
        '    "guard_cli_invalid_response",\n'
        '    "HOL Guard fallback did not return a valid decision. Retry the action.",\n'
        "  );\n"
        "}\n"
        "\n"
        "function modelVisibleBlockedReason(reason: string, reasonCode?: string): string {\n"
        "  if (\n"
        '    reasonCode === "guard_cli_recovery_timeout" ||\n'
        '    reasonCode === "daemon_hook_deadline_exhausted" ||\n'
        '    reasonCode === "daemon_hook_process_deadline_exhausted"\n'
        "  ) {\n"
        f'    return "HOL Guard did not finish reviewing this output before the {display_name} '
        'deadline. Retry the action.";\n'
        "  }\n"
        f'  const prefix = "HOL Guard blocked this tool output before {display_name} could use it.";\n'
        "  const approvalUrl = reason.match(/https?:\\/\\/\\S+/)?.[0]?.replace(/[.,;:]+$/, '');\n"
        "  const approvalHint = approvalUrl ? ` Human approval is pending in HOL Guard: ${approvalUrl}.` : '';\n"
        "  return `${prefix}${approvalHint} Do not retry the same tool call automatically; wait for the user to "
        "approve or change the task.`;\n"
        "}\n"
        "\n"
        "function blockedToolResult(reason: string, details: unknown) {\n"
        "  return {\n"
        '    content: [{ type: "text", text: reason }],\n'
        "    details,\n"
        "    isError: true,\n"
        "  };\n"
        "}\n"
        "\n"
        "function reviewedToolResult(content: unknown, details: unknown, isError?: boolean) {\n"
        "  let body = '';\n"
        "  if (Array.isArray(content)) {\n"
        "    body = boundedOutputText(content).value as string;\n"
        "  } else if (typeof content === 'string') {\n"
        "    body = content;\n"
        "  } else if (content !== undefined && content !== null) {\n"
        "    try { body = JSON.stringify(content); } catch {}\n"
        "  }\n"
        "  const result = {\n"
        '    content: body.length > 0 ? [{ type: "text", text: body }] : [],\n'
        "    details,\n"
        "  } as { content: unknown[]; details: unknown; isError?: boolean };\n"
        "  if (isError) result.isError = true;\n"
        "  return result;\n"
        "}\n"
        "\n" + APPROVAL_RESUME_HELPERS_SOURCE + "export default function (pi: ExtensionAPI) {\n"  # pyright: ignore[reportImplicitStringConcatenation]
        "  const blockedToolResults = new Map<string, string>();\n"
        "  type InputApprovalResumeBinding = {\n"
        "    generation: number;\n"
        "    sessionId: string;\n"
        "    cwd: string;\n"
        "  };\n"
        "  const pendingApprovalResumes = new Map<string, InputApprovalResumeBinding>();\n"
        "  const openedApprovalUrls = new Set<string>();\n"
        "  let approvalContinuationGeneration = 0;\n"
        "  let inputApprovalResumeGeneration = 0;\n"
        "  const invalidateToolApprovalContinuations = () => { approvalContinuationGeneration += 1; };\n"
        "  const invalidateInputApprovalResumes = () => { inputApprovalResumeGeneration += 1; };\n"
        "  const invalidateApprovalContinuations = () => {\n"
        "    invalidateToolApprovalContinuations();\n"
        "    invalidateInputApprovalResumes();\n"
        "  };\n"
        "  const approvalContinuationActivity = (): ApprovalContinuationActivity => {\n"
        "    const generation = approvalContinuationGeneration;\n"
        "    return () => generation === approvalContinuationGeneration;\n"
        "  };\n"
        "  const captureInputApprovalResumeBinding = (ctx: unknown): InputApprovalResumeBinding | null => {\n"
        "    const sessionId = contextSessionId(ctx);\n"
        "    const cwd = contextCwd(ctx);\n"
        "    if (!sessionId || !cwd) return null;\n"
        "    return { generation: inputApprovalResumeGeneration, sessionId, cwd };\n"
        "  };\n"
        "  const inputApprovalResumeBindingIsActive = (\n"
        "    ctx: unknown,\n"
        "    binding: InputApprovalResumeBinding | null,\n"
        "  ): boolean =>\n"
        "    binding !== null &&\n"
        "    binding.generation === inputApprovalResumeGeneration &&\n"
        "    contextSessionId(ctx) === binding.sessionId &&\n"
        "    contextCwd(ctx) === binding.cwd;\n"
        '  pi.on("agent_start", () => { invalidateApprovalContinuations(); });\n'
        '  pi.on("agent_end", () => { invalidateToolApprovalContinuations(); });\n'
        '  pi.on("session_start", () => { invalidateApprovalContinuations(); });\n'
        '  pi.on("session_shutdown", () => { invalidateApprovalContinuations(); });\n'
    )
